name: Test(Go)

on:
  workflow_call:
    # For now, inputs supports only three types: 'boolean', 'number' or 'string'.
    # workaround: https://github.community/t/reusable-workflow-with-strategy-matrix/205676/2
    inputs:
      os-versions:
        description: 'Stringfied JSON object listing GitHub-hosted runnners'
        default: '["ubuntu-22.04", "macos-14", "windows-2025"]'
        required: false
        type: string
      go-versions:
        description: 'Stringfied JSON object listing target Go versions'
        default: '["1.26.x", "1.25.x"]'
        required: false
        type: string
      pre:
        description: 'The commands to run in bash'
        default: ''
        required: false
        type: string

jobs:
  test:
    strategy:
      matrix:
        os-version: ${{ fromJson(inputs.os-versions) }}
        go-version: ${{ fromJson(inputs.go-versions) }}
    runs-on: ${{ matrix.os-version }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        check-latest: true
    - run: ${{ inputs.pre }}
      shell: bash
    - run: go test -race ./...
      shell: bash
