name: Test(Go)

on:
  workflow_call:
    # For now, inputs supports only three types: 'boolean', 'number' or 'string'.
    # workaround: https://github.community/t/reusable-workflow-with-strategy-matrix/205676/2
    inputs:
      os-versions:
        description: 'Stringfied JSON object listing GitHub-hosted runnners'
        default: '["ubuntu-22.04", "macos-14", "windows-2025"]'
        required: false
        type: string
      go-versions:
        description: 'Stringfied JSON object listing target Go versions'
        default: '["1.24.x", "1.23.x"]'
        required: false
        type: string
      pre:
        description: 'The commands to run in bash'
        default: ''
        required: false
        type: string

jobs:
  test:
    strategy:
      matrix:
        os-version: ${{ fromJson(inputs.os-versions) }}
        go-version: ${{ fromJson(inputs.go-versions) }}
    runs-on: ${{ matrix.os-version }}
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        check-latest: true
    - run: ${{ inputs.pre }}
      shell: bash
    - run: go test -race ./...
      shell: bash
